"$schema" = 'https://starship.rs/config-schema.json'
format = """
$directory\
$fill\
$cmd_duration\
$time\
$line_break\
$os\
$git_branch\
$character\
"""

[directory]
home_symbol = '  ~'
truncation_length = 1000
truncate_to_repo = false
read_only = " 󰌾"

[fill]
symbol = "─"
style = "#8c9cac"

[os]
format = "$symbol"
disabled = false
symbols.Macos = "  "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true

[gradle]
disabled = true

[java]
disabled = true

[character]
success_symbol = "[❯](#00bfff)"
error_symbol = "[❯](#f08080)"

[cmd_duration]
disabled = false
min_time = 100
show_milliseconds = true
format = "[ 󱦟 $duration](#b0c4de)"

[time]
disabled = false
format = "[  $time ](#b0c4de)"
