[general]
import = [
  # "~/.config/alacritty/themes/themes/ayu_mirage.toml",
  "~/.config/alacritty/custom_themes/aoharu.toml",
]

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 350
dimensions.lines = 100
position.x = 0
position.y = 0
padding.x = 30
padding.y = 10
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "UDEV Gothic 35NFLG"
normal.style = "Regular"
bold.family = "UDEV Gothic 35NFLG"
bold.style = "Regular"
italic.family = "UDEV Gothic 35NFLG"
italic.style = "Regular"
bold_italic.family = "UDEV Gothic 35NFLG"
bold_italic.style = "Regular"
# normal.family = "HackGen35 Console NF"
# normal.style = "Regular"
# bold.family = "HackGen35 Console NF"
# bold.style = "Regular"
# italic.family = "HackGen35 Console NF"
# italic.style = "Regular"
# bold_italic.family = "HackGen35 Console NF"
# bold_italic.style = "Regular"
size = 14

[colors]
cursor.text = "#66ccff"
cursor.cursor = "#66ccff"
# draw_bold_text_with_bright_colors = true

[cursor]
style.shape = "Beam"
style.blinking = "Always"
thickness = 0.4

[terminal]
shell.program = "/bin/zsh"
shell.args = [
  "-l",
  "-c",
  "zellij --layout vertical_2pain attach --index 0 --create"
]
