[general]
import = [
  # "~/.config/alacritty/themes/themes/nord.toml",
  "~/.config/alacritty/themes/themes/ayu_mik.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 350
dimensions.lines = 100
position.x = 0
position.y = 0
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "HackGen35 Console NF"
normal.style = "Regular"
bold.family = "HackGen35 Console NF"
bold.style = "Regular"
italic.family = "HackGen35 Console NF"
italic.style = "Regular"
bold_italic.family = "HackGen35 Console NF"
bold_italic.style = "Regular"
size = 14

[colors]
cursor.text = "#66ccff"
cursor.cursor = "#66ccff"

[cursor]
style.shape = "Beam"
style.blinking = "Always"
thickness = 0.35

[terminal]
shell.program = "/bin/zsh"
shell.args = [
  "-l",
  "-c",
  "zellij --layout vertical_2pain attach --index 0 --create"
]
